[package]
name = "physical_disks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows-drives = "0.5.0"
sysinfo = "0.20.3"
clap = "3.0.0-beta.4"
powershell_script = "1.0.2"
json = "0.12.4"
